Adding back valid Alt attribute, correcting an Aria issue upstream. [Work-In-Progess]
paypal/paypal-sdk-logos pull request #30
Opened 2021-04-05 18:10 UTC by BriceShatzer

## Problem  

[PayPal buttons have the incorrect aria-label](https://paypal.slack.com/archives/CDE52GDFT/p1603344735183900) 

## Solution 

Logos are currently not providing an `Alt` attribute, so when they are ultimately passed in to `funding/content.jsx` in [paypal-checkout-components](https://github.com/paypal/paypal-checkout-components/blob/50ec5294000d6adb0e916f6f4090d5b291458c45/src/funding/content.jsx#L71), they don't provide a text value, causing the aria-label to be rendered with a missing word.  

This adds back the alt tag for logo images which were removed [here](https://github.com/paypal/paypal-sdk-logos/pull/11/), solving this issue? 

 
## Additional Context
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-300

2021-04-05 19:16 UTC, mnicpt approved these changes

2021-04-05 19:17 UTC, mnicpt requested changes
Be sure to speak with Daniel first as to why he removed them.

2021-04-05 19:21 UTC, bluepnume commented
Looks like it was originally removed back in https://github.com/paypal/paypal-sdk-logos/commit/12906d66141d80bedc81db54319f393c8f3265b7#diff-7bbd7a260ca7576ce27319f8251c4616b2a4f838f1fa04de6d6257c95caabc08 -- @vishakha94 can you remind us the context, why this was removed?

Either way I think I'm perfectly happy to re-add this.

2021-04-27 23:11 UTC, vishakha94 commented
https://engineering.paypalcorp.com/jira/browse/PPPLMER-84424
Here’s the actual confluence page which talks about removing alt https://engineering.paypalcorp.com/confluence/pages/editpage.action?pageId=510894937
:this:  one will make more sense — see dev comments for 2&3

2022-06-28 15:13 UTC, closed without merging