Newapms
paypal/paypal-sdk-logos pull request #71
Opened 2022-11-02 00:00 UTC by JianyiGao

Add satispay logo and updated payu logo
Bump sdk constant version, related pr https://github.com/paypal/paypal-sdk-constants/pull/104

https://engineering.paypalcorp.com/jira/browse/DTALTPAY-1115

Tested locally with checkout components
![Screen Shot 2022-11-01 at 4 48 53 PM](https://user-images.githubusercontent.com/18254232/199363954-11afc2ef-6afe-444d-abbd-f7b18a32ddea.png)

2022-11-02 00:39 UTC, ericyupaypal requested changes

2022-11-02 00:39 UTC, ericyupaypal commented on src/logos/satispay/logo.jsx
> +    primary: "#2C2E2F",
Based on the UX design, the default logo could should be white rendered on the red background. The way you have it configured shows a dark color logo on the default red button background 
```suggestion
    primary: "#FFFFFF",
```
<img width="937" alt="Screen Shot 2022-11-01 at 5 35 25 PM" src="https://user-images.githubusercontent.com/9424291/199367484-22da6fb0-850e-4e90-a989-86b686605513.png">

2022-11-02 00:39 UTC, ericyupaypal commented on src/logos/payu/logo.jsx
> +    primary: "#A6C307",
Based on the UX design, the logo rendered on the white and silver buttons should be dark. The way you have it configured shows the default branded color.
```suggestion
    primary: "#2C2E2F",
    secondary: "#2C2E2F"
```
<img width="860" alt="Screen Shot 2022-11-01 at 5 39 17 PM" src="https://user-images.githubusercontent.com/9424291/199367782-4f1e433d-ee80-4878-883c-d714c45cceaa.png">

2022-11-02 23:43 UTC, ericyupaypal approved these changes
Appproved

2022-11-03 01:10 UTC, dtjones404 approved these changes
lgtm!

2022-11-03 16:42 UTC, merged